spring:
  application:
    name: book-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/book_db?createDatabaseIfNotExist=true
    username: root
    password: admin123